export const metadata = {
  title: "Registrar Venta - Red Salud Popular",
  description: "Generated by create next app",
};

export default function RegistrarVentaLayout({ children }) {
  return children;
}
