import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/contexts/AuthContext";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { FarmaciaProvider } from "@/contexts/FarmaciaContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inicio - Red Salud Popular",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <AuthProvider>
          <FarmaciaProvider>
            {children}
            <div id="modal" />
            <ToastContainer />
          </FarmaciaProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
