import { Inter } from "next/font/google";
import { Header } from "@/components/Header";
import styles from "./page.module.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Registrar Compra - Red Salud Popular",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Header />
        <main className={styles.main}>{children}</main>
        <div id="modal" />
      </body>
    </html>
  );
}
