import { Header } from "@/components/Header";
import styles from "./dashboard.module.css";

export const metadata = {
  title: "Dashboard - Red Salud Popular",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <>
      <Header />
      <main className={styles.main}>{children}</main>
    </>
  );
}
